In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [64]:
x0 = -6
x1 = 10
n = 40


# x_arr = (x0 + x1) - np.geomspace(x0, x1, n)
# y_arr = np.array([2]*n)
# plt.scatter(x_arr,y_arr)
# plt.show()

geom = 2 - np.geomspace(1, 2, n)
x_arr = x0 + geom*(x1-x0)
plt.scatter(x_arr,y_arr)
plt.show()

NameError: name 'reverse' is not defined

In [2]:
import matplotlib.pyplot as plt
import numpy

w = 7195
h = 3841

im_np = numpy.random.rand(h, w)

# fig = plt.figure(frameon=False, figsize=(w/1000,h/1000))
# ax = plt.Axes(fig, [0., 0., 1., 1.])
# # ax.set_axis_off()
# ax.axis('off')
# fig.add_axes(ax)
# ax.imshow(im_np, aspect='equal')
# fig.savefig('figure.png', dpi=1000)


# fig, ax = plt.subplots(figsize=(w/1000,h/1000))
# # ax = plt.Axes(fig, [0., 0., 1., 1.])
# ax.set_axis_off()
# ax.imshow(im_np, aspect='equal')
# fig.savefig('figure2.png', dpi=1000)

In [3]:
plt.imsave(fname='figure3.png', format='png', arr=im_np)

In [6]:
import numpy as np

In [7]:
x = np.array([5,3,0,3,1,3,0])

y = np.ma.masked_where(x==0, x)
print(y)

[5 3 -- 3 1 3 --]


In [121]:
x = np.zeros((3,5))
print(x)

for i in range(3):
    x[i] = [(i+1)*j for j in range(5)]
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]]


In [35]:
def multip(x):
    if np.isnan(np.abs(x)):
        print('asdf')
    return x*x

In [44]:
mapfun = np.vectorize(multip)

In [52]:
complex(0,0)**2

0j

In [51]:
# y = mapfun(x)
print(np.vectorize(multip)(x))

[[  0.   1.   4.   9.  16.]
 [  0.   4.  16.  36.  64.]
 [  0.   9.  36.  81. 144.]]


In [89]:
m = np.array([[multip(j) for j in i] for i in x])
print(m)

[[  0.   1.   4.   9.  16.]
 [  0.   4.  16.  36.  64.]
 [  0.   9.  36.  81. 144.]]
